Repository Lumina-DEX/lumina, pull requests merged in 2025-03, with the labels that each got.

#43 docs: add contracts documentation
  .github/workflows/contract-docs.yaml
  .vscode/lumina.code-workspace
  package.json
  packages/contracts-docs/.nojekyll
  packages/contracts-docs/.vscode/settings.json
  packages/contracts-docs/assets/highlight.css
  packages/contracts-docs/assets/icons.js
  packages/contracts-docs/assets/icons.svg
  packages/contracts-docs/assets/main.js
  packages/contracts-docs/assets/navigation.js
  packages/contracts-docs/assets/search.js
  packages/contracts-docs/assets/style.css
  packages/contracts-docs/classes/AddLiquidityEvent.html
  packages/contracts-docs/classes/BalanceChangeEvent.html
  packages/contracts-docs/classes/BurnEvent.html
  packages/contracts-docs/classes/FungibleToken.html
  packages/contracts-docs/classes/FungibleTokenAdmin.html
  packages/contracts-docs/classes/MintEvent.html
  packages/contracts-docs/classes/PauseEvent.html
  packages/contracts-docs/classes/Pool.html
  packages/contracts-docs/classes/PoolCreationEvent.html
  packages/contracts-docs/classes/PoolData.html
  packages/contracts-docs/classes/PoolFactory.html
  packages/contracts-docs/classes/PoolTokenHolder.html
  packages/contracts-docs/classes/SetAdminEvent.html
  packages/contracts-docs/classes/SwapEvent.html
  packages/contracts-docs/classes/WithdrawLiquidityEvent.html
  packages/contracts-docs/functions/mulDiv.html
  packages/contracts-docs/functions/mulDivMod.html
  packages/contracts-docs/index.html
  packages/contracts-docs/interfaces/FungibleTokenAdminDeployProps.html
  packages/contracts-docs/interfaces/PoolDataDeployProps.html
  packages/contracts-docs/interfaces/PoolDeployProps.html
  packages/contracts-docs/modules.html
  packages/contracts-docs/package.json
  packages/contracts-docs/types/FungibleTokenAdminBase.html
  packages/contracts-docs/variables/FungibleTokenErrors.html
  packages/contracts-docs/variables/contractData.html
  packages/contracts-docs/variables/contractHash.html
  packages/contracts-docs/variables/contractHolderData.html
  packages/contracts-docs/variables/contractHolderHash.html
  packages/contracts/.gitignore
  packages/contracts/README.md
  packages/contracts/package.json
  packages/contracts/src/farming/Farm.ts
  packages/contracts/src/farming/FarmReward.ts
  packages/contracts/src/farming/FarmRewardTokenHolder.ts
  packages/contracts/src/farming/FarmTokenHolder.ts
  packages/contracts/src/pool/IPoolState.ts
  packages/contracts/src/pool/Pool.ts
  packages/contracts/src/pool/PoolFactory.ts
  packages/contracts/src/pool/PoolTokenHolder.ts
  packages/contracts/tests/Factory.test.ts
  packages/contracts/tests/Farm.Token.test.ts
  packages/contracts/tests/Farm.test.ts
  packages/contracts/tests/Faucet.test.ts
  packages/contracts/tests/PoolData.test.ts
  packages/contracts/tests/PoolToken.test.ts
Labels: documentation

#44 ci: fix contracts docs build
  .github/workflows/contract-docs.yaml
  .github/workflows/lint-build.yaml
Labels: CI/CD

#47 feat(sdk): update fees
  .changeset/hip-lions-thank.md
  packages/contracts/src/pool/Pool.ts
  packages/contracts/src/pool/PoolFactory.ts
  packages/dex-ui/README.md
  packages/sdk/src/machines/luminadex/machine.ts
Labels: feature

#50 docs(sdk): add docs website
  .github/workflows/deploy-test-apps.yml
  .github/workflows/sdk-docs.yaml
  .gitignore
  .npmrc
  README.md
  lefthook.yml
  package.json
  packages/sdk-test-react/src/routes/index.tsx
  packages/sdk-test-react/wrangler.jsonc
  packages/sdk-test-vue/wrangler.jsonc
  packages/sdk/.gitignore
  packages/sdk/README.md
  packages/sdk/docs/.vitepress/config.ts
  packages/sdk/docs/.vitepress/theme/index.ts
  packages/sdk/docs/.vitepress/theme/style.css
  packages/sdk/docs/api/dex-machine.md
  packages/sdk/docs/api/helpers.md
  packages/sdk/docs/api/overview.md
  packages/sdk/docs/api/wallet-machine.md
  packages/sdk/docs/guide/core-concepts.md
  packages/sdk/docs/guide/fetching-data.md
  packages/sdk/docs/guide/getting-started.md
  packages/sdk/docs/guide/managing-liquidity.md
  packages/sdk/docs/guide/react-integration.md
  packages/sdk/docs/guide/swapping-tokens.md
  packages/sdk/docs/guide/vue-integration.md
  packages/sdk/docs/guide/wallet-connection.md
  packages/sdk/docs/index.md
  packages/sdk/docs/public/apple-touch-icon.png
  packages/sdk/docs/public/favicon-96x96.png
  packages/sdk/docs/public/favicon.ico
  packages/sdk/docs/public/favicon.svg
  packages/sdk/docs/public/logo.png
  packages/sdk/docs/public/site.webmanifest
  packages/sdk/docs/public/web-app-manifest-192x192.png
  packages/sdk/docs/public/web-app-manifest-512x512.png
  packages/sdk/docs/worker.ts
  packages/sdk/package.json
  packages/sdk/wrangler.jsonc
  pnpm-lock.yaml
Labels: documentation

#52 fix: supply liquidity
  .changeset/chatty-cats-dance.md
  packages/contracts/src/pool/Pool.ts
  packages/contracts/src/pool/PoolFactory.ts
  packages/contracts/src/utils/helper.ts
  packages/contracts/src/utils/verificationKey.ts
  packages/contracts/tests/Factory.test.ts
  packages/contracts/tests/PoolToken.test.ts
Labels: fix

#49 feat: add cdn versioning system
  .github/workflows/cdn-preview.yaml
  .github/workflows/cdn.yaml
  .github/workflows/release.yaml
  lage.config.cjs
  package.json
  packages/contracts-cdn/.gitignore
  packages/contracts-cdn/package.json
  packages/contracts-cdn/scripts/create-cache.ts
  packages/contracts-cdn/src/index.ts
  packages/contracts-cdn/test/cache.spec.ts
  packages/contracts-cdn/test/generated-cache.ts
  packages/contracts-cdn/wrangler.jsonc
  packages/contracts-cdn/wrangler.toml
  packages/sdk/src/constants/index.ts
  packages/sdk/src/dex/cache.ts
  packages/sdk/tsconfig.json
  packages/sdk/wrangler.jsonc
  pnpm-lock.yaml
  scripts/version.ts
  tsconfig.json
Labels: feature

#56 fix: Bug loading sdk bundle url
  .changeset/weak-turkeys-relate.md
  CODE_OF_CONDUCT.md
  packages/sdk/src/constants/index.ts
Labels: fix
