Repository Lumina-DEX/lumina, pull requests merged in 2025-04, with the labels that each got.

#58 chore: add bsl license
  LICENSE
  packages/contracts-cdn/LICENSE
  packages/contracts/LICENSE
  packages/dex-ui/LICENSE
  packages/lumina-tokens/LICENSE
  packages/order-book/LICENSE.md
  packages/sdk-test-react/LICENSE
  packages/sdk-test-vue/LICENSE
  packages/sdk/LICENSE
  packages/signer/LICENSE
Labels: chore

#61 chore: update lumina order book license
  packages/order-book/LICENSE.md
Labels: chore

#62 chore: add sdk disclaimer
  packages/sdk/README.md
Labels: chore

#63 feat: multiple token fetches
  .changeset/fuzzy-tables-divide.md
  packages/sdk-test-react/src/routes/index.tsx
  packages/sdk-test-vue/app.vue
  packages/sdk/docs/api/dex-machine.md
  packages/sdk/docs/api/wallet-machine.md
  packages/sdk/docs/guide/managing-liquidity.md
  packages/sdk/docs/guide/react-integration.md
  packages/sdk/docs/guide/vue-integration.md
  packages/sdk/docs/guide/wallet-connection.md
  packages/sdk/package.json
  packages/sdk/src/graphql/mina-env.d.ts
  packages/sdk/src/graphql/mina.graphql
  packages/sdk/src/machines/luminadex/machine.ts
  packages/sdk/src/machines/luminadex/types.ts
  packages/sdk/src/machines/wallet/machine.ts
  packages/sdk/src/machines/wallet/types.ts
Labels: feature

#65 feat: add llms.txt to luminadocs
  packages/sdk/docs/.vitepress/config.ts
  packages/sdk/docs/public/_redirects
  packages/sdk/package.json
  pnpm-lock.yaml
Labels: feature

#66 feat: add hash and url
  .changeset/fair-cars-march.md
  packages/sdk/docs/public/_redirects
  packages/sdk/src/helpers/transfer.ts
  packages/sdk/src/machines/luminadex/machine.ts
  packages/sdk/src/machines/luminadex/types.ts
Labels: feature

#67 fix: add custom fund new account to support zeko fee
  .changeset/selfish-chefs-exist.md
  packages/sdk/src/dex/luminadex-worker.ts
Labels: fix
