Repository Lumina-DEX/lumina, pull requests merged in 2025-02, with the labels that each got.

#26 fix(sdk): update signer and user0 for mina:testnet
  .changeset/five-queens-cover.md
  packages/lumina-tokens/deno.lock
  packages/sdk/src/constants/index.ts
  packages/sdk/src/dex/luminadex-worker.ts
  packages/sdk/src/machines/luminadex/machine.ts
Labels: fix

#28 fix(cdn): token sync resets db
  .github/workflows/release.yaml
  packages/contracts-cdn/src/http.ts
  packages/contracts-cdn/src/index.ts
  packages/contracts-cdn/test/api.spec.ts
  packages/sdk-test-vue/app.vue
  packages/sdk-test-vue/modules/sdk-version.ts
  packages/sdk-test-vue/package.json
  pnpm-lock.yaml
Labels: fix

#29 feat(sdk): updated chain information
  .changeset/dry-turkeys-relax.md
  packages/contracts-cdn/drizzle/generated/0001_sleepy_vanisher.sql
  packages/contracts-cdn/drizzle/generated/meta/0001_snapshot.json
  packages/contracts-cdn/drizzle/generated/meta/_journal.json
  packages/contracts-cdn/drizzle/generated/migrations.js
  packages/contracts-cdn/drizzle/schema.ts
  packages/contracts-cdn/package.json
  packages/contracts-cdn/scripts/generate-token-list.ts
  packages/contracts-cdn/src/do.ts
  packages/contracts-cdn/src/helper.ts
  packages/contracts-cdn/src/index.ts
  packages/contracts-cdn/test/api.spec.ts
  packages/contracts-cdn/test/db.spec.ts
  packages/lumina-tokens/deno.json
  packages/lumina-tokens/src/main.ts
  packages/sdk-test-react/src/routes/index.tsx
  packages/sdk-test-vue/app.vue
  packages/sdk/README.md
  packages/sdk/src/constants/index.ts
  packages/sdk/src/helpers/blockchain.ts
  packages/sdk/src/machines/luminadex/machine.ts
  packages/sdk/src/machines/wallet/machine.ts
Labels: feature

#31 fix(sdk): mina devnet token balances
  packages/sdk/src/machines/wallet/machine.ts
  packages/sdk/src/machines/wallet/types.ts
Labels: fix

#32 chore: release sdk fix
  .changeset/modern-lions-vanish.md
Labels: chore

#36 fix(sdk): swap settings
  .changeset/real-turkeys-hammer.md
  packages/sdk/src/constants/index.ts
  packages/sdk/src/dex/luminadex-worker.ts
  packages/sdk/src/dex/utils.ts
  packages/sdk/src/machines/luminadex/machine.ts
Labels: fix

#40 feat: create signer api
  .vscode/lumina.code-workspace
  packages/signer/.env.test
  packages/signer/.vscode/settings.json
  packages/signer/README.md
  packages/signer/package.json
  packages/signer/src/env.d.ts
  packages/signer/src/main.ts
  packages/signer/tsconfig.json
  pnpm-lock.yaml
Labels: feature

#41 fix: swap from token to mina
  .changeset/tall-planes-live.md
  packages/sdk/src/dex/luminadex-worker.ts
Labels: fix
